stages:
  - build
  - deploy

variables:
  MAVEN_CLI_OPTS: "--batch-mode -Dmaven.repo.local=.m2/repository"
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""

maven:
  stage: build
  image: maven:3.8.4-openjdk-11
  script:
    - mvn $MAVEN_CLI_OPTS clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 day

docker_image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t 93.125.42.36:8123/repository/docker-release/test-service:${CI_COMMIT_REF_NAME} .
    - docker push 93.125.42.36:8123/repository/docker-release/test-service:${CI_COMMIT_REF_NAME}
  only:
    - main
    - merge_requests

kubernetes:
  stage: deploy
  image: bitnami/kubectl:latest
  script:
    - kubectl apply -f k8s-manifest/deployment.yaml
    - kubectl apply -f k8s-manifest/service.yaml
    - kubectl apply -f k8s-manifest/ingress.yaml
  only:
    - main
