apiVersion: v1
kind: Service
metadata:
  name: my-deployment
  namespace: javaguru
spec:
  selector:
    app: my-deployment
  ports:
    - name: http
      port: 9090
      targetPort: http
  type: ClusterIP
